[package]
name    = "tsp-mt"
version = "0.1.0"
edition = "2024"
build   = "build.rs"

[dependencies]
rand       = "0.9.2"
rayon      = "1.8"
ryu        = "1.0"
kiddo      = "5.2.4"
map_3d     = "0.1.5"
h3o        = "0.9.4"
log        = "0.4"
env_logger = "0.11"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
opt-level     = "s"
lto           = true
codegen-units = 1
strip         = true
