[package]
name    = "tsp-mt"
version = "0.1.0"
edition = "2024"

[dependencies]
rand     = "0.9.2"
rayon    = "1.8"
num_cpus = "1.17.0"
ryu      = "1.0"
kiddo    = "5.2.4"
geo      = "0.31.0"
map_3d   = "0.1.5"
h3o      = "0.7"

[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

[profile.release]
opt-level     = "s"
lto           = true
codegen-units = 1
strip         = true

# Profile for distribution
[profile.dist]
inherits      = "release"
opt-level     = 3
lto           = true
codegen-units = 1
strip         = true
